# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Alert.io' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 pod 'Firebase/Core'	
 pod 'Firebase/Auth'
  # Pods for Alert.io

  target 'Alert.ioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Alert.ioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
